export const SHOW_ALL_ADMINS ="SHOW_ALL_ADMINS";
export const SHOW_ALL_DOCTORS ="SHOW_ALL_DOCTORS";
export const SHOW_ALL_PATIENTS ="SHOW_ALL_PATIENTS";
export const SHOW_ALL_NURSES ="SHOW_ALL_NURSES";